---
version: '3.3'

networks:
  frontend:
  backend:
  database:
  satellite:

services:

  consul-master:
    image: bodsch/docker-consul
    container_name: consul-master
    hostname: consul-master
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
      - 8600:8600
      - 8600:8600/udp
      - 53:53
    environment:
      - CONSUL_UI_BETA=true
    command: 'agent -data-dir /data -server -bootstrap-expect 1 -ui -client=0.0.0.0'
    networks:
      - backend

  database:
    image: bodsch/docker-mysql:latest
    container_name: database
    hostname: database
    environment:
      - MYSQL_SYSTEM_USER=root
      - MYSQL_ROOT_PASS=vYUQ14SGVrJRi69PsujC
      - CONFIG_BACKEND=consul
      - CONSUL=consul-master
    volumes:
      - /etc/localtime:/etc/localtime:ro
    links:
      - consul-master
    networks:
      - backend
      - database

#  # icingaweb2
#  #
#  icingaweb2:
#    image: bodsch/docker-icingaweb2:latest
#    container_name: icingaweb2
#    hostname: icingaweb2.matrix.lan
#    ports:
#      - 80:80
#    environment:
#      - CONFIG_BACKEND=consul
#      - CONSUL=consul-master
#      #
#      - MYSQL_HOST=database
#      - MYSQL_ROOT_USER=root
#      - MYSQL_ROOT_PASS=vYUQ14SGVrJRi69PsujC
#      - IDO_DATABASE_NAME=icinga2core
#      - IDO_PASSWORD=qUVuLTk9oEDUV0A
#      - ICINGA2_MASTER=icinga2-master.matrix.lan
#      - ICINGA2_CMD_API_USER=root
#      - ICINGA2_CMD_API_PASS=icinga
#      - ICINGAWEB2_USERS=icinga:icinga,foo:bar
#    links:
#      - icinga2-master:icinga2-master.matrix.lan
#      - database
#    networks:
#      - database
#      - frontend
#      - backend
#
  # the Icinga2 Master
  # includes a certificate service to create and provide a icinga certificate
  icinga2-master:
#    image: bodsch/docker-icinga2:2.8.4-master-dev
    build:
      context: icinga2-master
      dockerfile: Dockerfile
      args:
        - BUILD_DATE=${BUILD_DATE}
        - ICINGA2_VERSION=${ICINGA2_VERSION}
        - CERT_SERVICE_VERSION=0.17.6
    container_name: icinga2-master
    hostname: icinga2-master.matrix.lan
    restart: always
    privileged: true
    ports:
      - 5665:5665
      - 8080:8080
    environment:
      - CONFIG_BACKEND=consul
      - CONSUL=consul-master
      #
      - ICINGA2_API_USERS=root:icinga,dashing:dashing,cert:foo-bar
      - LOG_LEVEL=debug
      - MYSQL_HOST=database
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASS=vYUQ14SGVrJRi69PsujC
      - IDO_PASSWORD=qUVuLTk9oEDUV0A
      # environment variables for the certificates service
      - ICINGA2_MASTER=icinga2-master.matrix.lan
      - BASIC_AUTH_USER=admin
      - BASIC_AUTH_PASS=admin
      - CERT_SERVICE_BA_USER=admin
      - CERT_SERVICE_BA_PASSWORD=admin
      - CERT_SERVICE_API_USER=root
      - CERT_SERVICE_API_PASSWORD=icinga
      - CERT_SERVICE_SERVER=icinga2-master
      - CERT_SERVICE_PORT=8080
      - CERT_SERVICE_PATH=/
      - CARBON_HOST=
      - CARBON_PORT=2003
      - DEMO_DATA=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
    links:
      - database
      - consul-master
    networks:
      - database
      - backend


#  # the first icinga2 satellite
#  # ask the master above for an certificate
#  #
#  # this satellite should work, the BA is correct
#  icinga2-satellite-1:
#    build:
#      context: icinga2-satellite
#      dockerfile: Dockerfile
#      args:
#        - BUILD_DATE=${BUILD_DATE}
#        - ICINGA2_VERSION=${ICINGA2_VERSION}
#    container_name: icinga2-satellite-1
#    hostname: icinga2-satellite-1.matrix.lan
#    restart: always
#    privileged: true
#    environment:
#      - CONFIG_BACKEND=consul
#      - CONSUL=consul-master
#      #
#      - ICINGA2_MASTER=icinga2-master.matrix.lan
#      - ICINGA2_PARENT=icinga2-master.matrix.lan
#      - CERT_SERVICE_BA_USER=admin
#      - CERT_SERVICE_BA_PASSWORD=admin
#      - CERT_SERVICE_API_USER=root
#      - CERT_SERVICE_API_PASSWORD=icinga
#      - CERT_SERVICE_SERVER=icinga2-master.matrix.lan
#      - CERT_SERVICE_PORT=8080
#      - CERT_SERVICE_PATH=/
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#    links:
#      - icinga2-master:icinga2-master.matrix.lan
#      - consul-master
#    networks:
#      - backend
#      - satellite
#
  # the second icinga2 satellite
  # ask the master above for an certificate
  #
  # this satellite should fail, because the BA is faulty
#  icinga2-satellite-2:
#    build: .
#    container_name: icinga2-satellite-2
#    hostname: icinga2-satellite-2.matrix.lan
#    restart: always
#    privileged: true
#    environment:
#      - ICINGA2_MASTER=icinga2-master.matrix.lan
#      - ICINGA2_PARENT=icinga2-master.matrix.lan
#      - CERT_SERVICE_BA_USER=foofoo
#      - CERT_SERVICE_BA_PASSWORD=barbar
#      - CERT_SERVICE_API_USER=root
#      - CERT_SERVICE_API_PASSWORD=icinga
#      - CERT_SERVICE_SERVER=icinga2-master
#      - CERT_SERVICE_PORT=8080
#      - CERT_SERVICE_PATH=/
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#    links:
#      - icinga2-master:icinga2-master.matrix.lan

#  # the third icinga2 satellite
#  # ask the master above for an certificate
#  #
#  # this satellite should work, the BA is correct
#  icinga2-satellite-3:
#    build: .
#    container_name: icinga2-satellite-3
#    hostname: icinga2-satellite-3.matrix.lan
#    restart: always
#    privileged: true
#    environment:
#      - ICINGA2_MASTER=icinga2-master.matrix.lan
#      - ICINGA2_PARENT=icinga2-master.matrix.lan
#      - CERT_SERVICE=true
#      - CERT_SERVICE_BA_USER=foofoo
#      - CERT_SERVICE_BA_PASSWORD=barbar
#      - CERT_SERVICE_API_USER=root
#      - CERT_SERVICE_API_PASSWORD=icinga
#      - CERT_SERVICE_SERVER=icinga2-master
#      - CERT_SERVICE_PORT=8080
#      - CERT_SERVICE_PATH=/
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /tmp/docker-data/icinga2-satellite-3:/var/lib/icinga2
#    links:
#      - icinga2-master:icinga2-master.matrix.lan
#
#
#  # the fourth icinga2 satellite
#  # ask the master above for an certificate
#  #
#  # this satellite should fail, because the BA is faulty
#  icinga2-satellite-4:
#    build: .
#    container_name: icinga2-satellite-4
#    hostname: icinga2-satellite-4.matrix.lan
#    restart: always
#    privileged: true
#    environment:
#      - ICINGA2_MASTER=icinga2-master.matrix.lan
#      - ICINGA2_PARENT=icinga2-master.matrix.lan
#      - CERT_SERVICE=true
#      - CERT_SERVICE_BA_USER=foofoo
#      - CERT_SERVICE_BA_PASSWORD=barbar
#      - CERT_SERVICE_API_USER=root
#      - CERT_SERVICE_API_PASSWORD=icinga
#      - CERT_SERVICE_SERVER=icinga2-master
#      - CERT_SERVICE_PORT=8080
#      - CERT_SERVICE_PATH=/
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /tmp/docker-data/icinga2-satellite-4:/var/lib/icinga2
#    links:
#      - icinga2-master:icinga2-master.matrix.lan
#

#  # a icinga2 agent - connected to an satellite
#  # ask the master above for an certificate
#  icinga2-agent-2.1:
#    build: .
#    container_name: icinga2-agent-2-1
#    hostname: icinga2-agent-2-1.matrix.lan
#    privileged: true
#    environment:
#      - ICINGA2_MASTER=icinga2-master.matrix.lan
#      - ICINGA2_PARENT=icinga2-satellite-2
#      - CERT_SERVICE=true
#      - CERT_SERVICE_BA_USER=admin
#      - CERT_SERVICE_BA_PASSWORD=admin
#      - CERT_SERVICE_API_USER=root
#      - CERT_SERVICE_API_PASSWORD=icinga
#      - CERT_SERVICE_SERVER=icinga2-master
#      - CERT_SERVICE_PORT=4567
#      - CERT_SERVICE_PATH=/
#    volumes:
#      - /tmp/docker-data/icinga2-agent-2.1:/srv
#    links:
#      - icinga2-satellite-2:icinga2-satellite-2.matrix.lan
#
